-- =============================================================================
-- TN Election 2026 – Seed Data
-- Generated from CSV files in /data/
-- =============================================================================

-- Section 1: Districts (38 rows)
INSERT INTO districts (name, slug) VALUES
  ('Ariyalur', 'ariyalur'),
  ('Chengalpattu', 'chengalpattu'),
  ('Chennai', 'chennai'),
  ('Coimbatore', 'coimbatore'),
  ('Cuddalore', 'cuddalore'),
  ('Dharmapuri', 'dharmapuri'),
  ('Dindigul', 'dindigul'),
  ('Erode', 'erode'),
  ('Kallakurichi', 'kallakurichi'),
  ('Kancheepuram', 'kancheepuram'),
  ('Kanniyakumari', 'kanniyakumari'),
  ('Karur', 'karur'),
  ('Krishnagiri', 'krishnagiri'),
  ('Madurai', 'madurai'),
  ('Mayiladuthurai', 'mayiladuthurai'),
  ('Nagapattinam', 'nagapattinam'),
  ('Namakkal', 'namakkal'),
  ('Nilgiris', 'nilgiris'),
  ('Perambalur', 'perambalur'),
  ('Pudukkottai', 'pudukkottai'),
  ('Ramanathapuram', 'ramanathapuram'),
  ('Ranipet', 'ranipet'),
  ('Salem', 'salem'),
  ('Sivaganga', 'sivaganga'),
  ('Tenkasi', 'tenkasi'),
  ('Thanjavur', 'thanjavur'),
  ('Theni', 'theni'),
  ('Thiruvallur', 'thiruvallur'),
  ('Thiruvarur', 'thiruvarur'),
  ('Thoothukudi', 'thoothukudi'),
  ('Tiruchirappalli', 'tiruchirappalli'),
  ('Tirunelveli', 'tirunelveli'),
  ('Tirupathur', 'tirupathur'),
  ('Tiruppur', 'tiruppur'),
  ('Tiruvannamalai', 'tiruvannamalai'),
  ('Vellore', 'vellore'),
  ('Villupuram', 'villupuram'),
  ('Virudhunagar', 'virudhunagar')
ON CONFLICT (slug) DO NOTHING;

-- Section 2: Parties (16 rows)
INSERT INTO parties (name, abbreviation, slug, alliance, color_hex) VALUES
  ('Dravida Munnetra Kazhagam', 'DMK', 'dmk', 'INDIA', '#E63946'),
  ('All India Anna Dravida Munnetra Kazhagam', 'AIADMK', 'aiadmk', NULL, '#006400'),
  ('Bharatiya Janata Party', 'BJP', 'bjp', 'NDA', '#FF6600'),
  ('Indian National Congress', 'INC', 'inc', 'INDIA', '#138808'),
  ('Pattali Makkal Katchi', 'PMK', 'pmk', 'NDA', '#1a7a1a'),
  ('Viduthalai Chiruthaigal Katchi', 'VCK', 'vck', 'INDIA', '#1a3a8c'),
  ('Tamilaga Vettri Kazhagam', 'TVK', 'tvk', NULL, '#0d9488'),
  ('Marumalarchi Dravida Munnetra Kazhagam', 'MDMK', 'mdmk', 'INDIA', '#cc0000'),
  ('Communist Party of India (Marxist)', 'CPIM', 'cpim', 'INDIA', '#cc0000'),
  ('Communist Party of India', 'CPI', 'cpi', 'INDIA', '#cc0000'),
  ('Indian Union Muslim League', 'IUML', 'iuml', 'INDIA', '#006400'),
  ('Kongu Nadu Munnetra Kazhagam', 'KNMK', 'knmk', NULL, '#8B4513'),
  ('All India Majlis-e-Ittehadul Muslimeen', 'AIMIM', 'aimim', NULL, '#006400'),
  ('Naam Tamilar Katchi', 'NTK', 'ntk', NULL, '#FF6600'),
  ('Bahujan Samaj Party', 'BSP', 'bsp', NULL, '#1a3a8c'),
  ('Independent', 'IND', 'ind', NULL, '#94a3b8')
ON CONFLICT (slug) DO NOTHING;

-- Section 3: Constituencies (234 rows)
INSERT INTO constituencies (name, slug, constituency_no, district_id, reserved_for) VALUES
  ('Gummidipoondi', 'gummidipoondi', 1, (SELECT id FROM districts WHERE slug = 'thiruvallur'), 'general'),
  ('Ponneri', 'ponneri', 2, (SELECT id FROM districts WHERE slug = 'thiruvallur'), 'sc'),
  ('Tiruttani', 'tiruttani', 3, (SELECT id FROM districts WHERE slug = 'thiruvallur'), 'general'),
  ('Sholingur', 'sholingur', 4, (SELECT id FROM districts WHERE slug = 'vellore'), 'general'),
  ('Katpadi', 'katpadi', 5, (SELECT id FROM districts WHERE slug = 'vellore'), 'general'),
  ('Ranipet', 'ranipet', 6, (SELECT id FROM districts WHERE slug = 'ranipet'), 'general'),
  ('Arcot', 'arcot', 7, (SELECT id FROM districts WHERE slug = 'ranipet'), 'general'),
  ('Vellore', 'vellore', 8, (SELECT id FROM districts WHERE slug = 'vellore'), 'general'),
  ('Anaikattu', 'anaikattu', 9, (SELECT id FROM districts WHERE slug = 'vellore'), 'general'),
  ('Kilvaithinankuppam', 'kilvaithinankuppam', 10, (SELECT id FROM districts WHERE slug = 'vellore'), 'sc'),
  ('Gudiyatham', 'gudiyatham', 11, (SELECT id FROM districts WHERE slug = 'vellore'), 'general'),
  ('Vaniyambadi', 'vaniyambadi', 12, (SELECT id FROM districts WHERE slug = 'tirupathur'), 'general'),
  ('Ambur', 'ambur', 13, (SELECT id FROM districts WHERE slug = 'tirupathur'), 'general'),
  ('Jolarpet', 'jolarpet', 14, (SELECT id FROM districts WHERE slug = 'tirupathur'), 'general'),
  ('Tirupattur', 'tirupattur', 15, (SELECT id FROM districts WHERE slug = 'tirupathur'), 'general'),
  ('Uthangarai', 'uthangarai', 16, (SELECT id FROM districts WHERE slug = 'krishnagiri'), 'st'),
  ('Bargur', 'bargur', 17, (SELECT id FROM districts WHERE slug = 'krishnagiri'), 'general'),
  ('Krishnagiri', 'krishnagiri', 18, (SELECT id FROM districts WHERE slug = 'krishnagiri'), 'general'),
  ('Veppanahalli', 'veppanahalli', 19, (SELECT id FROM districts WHERE slug = 'krishnagiri'), 'general'),
  ('Hosur', 'hosur', 20, (SELECT id FROM districts WHERE slug = 'krishnagiri'), 'general'),
  ('Thalli', 'thalli', 21, (SELECT id FROM districts WHERE slug = 'krishnagiri'), 'sc'),
  ('Palacodu', 'palacodu', 22, (SELECT id FROM districts WHERE slug = 'dharmapuri'), 'general'),
  ('Pennagaram', 'pennagaram', 23, (SELECT id FROM districts WHERE slug = 'dharmapuri'), 'general'),
  ('Dharmapuri', 'dharmapuri', 24, (SELECT id FROM districts WHERE slug = 'dharmapuri'), 'general'),
  ('Pappireddipatti', 'pappireddipatti', 25, (SELECT id FROM districts WHERE slug = 'dharmapuri'), 'sc'),
  ('Harur', 'harur', 26, (SELECT id FROM districts WHERE slug = 'dharmapuri'), 'general'),
  ('Omalur', 'omalur', 27, (SELECT id FROM districts WHERE slug = 'salem'), 'general'),
  ('Mettur', 'mettur', 28, (SELECT id FROM districts WHERE slug = 'salem'), 'general'),
  ('Edappadi', 'edappadi', 29, (SELECT id FROM districts WHERE slug = 'salem'), 'general'),
  ('Sankari', 'sankari', 30, (SELECT id FROM districts WHERE slug = 'salem'), 'general'),
  ('Salem (West)', 'salem-west', 31, (SELECT id FROM districts WHERE slug = 'salem'), 'general'),
  ('Salem (North)', 'salem-north', 32, (SELECT id FROM districts WHERE slug = 'salem'), 'general'),
  ('Salem (South)', 'salem-south', 33, (SELECT id FROM districts WHERE slug = 'salem'), 'sc'),
  ('Veerapandi', 'veerapandi', 34, (SELECT id FROM districts WHERE slug = 'salem'), 'general'),
  ('Rasipuram', 'rasipuram', 35, (SELECT id FROM districts WHERE slug = 'namakkal'), 'general'),
  ('Senthamangalam', 'senthamangalam', 36, (SELECT id FROM districts WHERE slug = 'namakkal'), 'st'),
  ('Namakkal', 'namakkal', 37, (SELECT id FROM districts WHERE slug = 'namakkal'), 'general'),
  ('Paramathi-Velur', 'paramathi-velur', 38, (SELECT id FROM districts WHERE slug = 'namakkal'), 'general'),
  ('Tiruchengodu', 'tiruchengodu', 39, (SELECT id FROM districts WHERE slug = 'namakkal'), 'general'),
  ('Kumarapalayam', 'kumarapalayam', 40, (SELECT id FROM districts WHERE slug = 'namakkal'), 'general'),
  ('Erode (East)', 'erode-east', 41, (SELECT id FROM districts WHERE slug = 'erode'), 'general'),
  ('Erode (West)', 'erode-west', 42, (SELECT id FROM districts WHERE slug = 'erode'), 'sc'),
  ('Modakkurichi', 'modakkurichi', 43, (SELECT id FROM districts WHERE slug = 'erode'), 'general'),
  ('Perundurai', 'perundurai', 44, (SELECT id FROM districts WHERE slug = 'erode'), 'general'),
  ('Bhavani', 'bhavani', 45, (SELECT id FROM districts WHERE slug = 'erode'), 'general'),
  ('Anthiyur', 'anthiyur', 46, (SELECT id FROM districts WHERE slug = 'erode'), 'general'),
  ('Gobichettipalayam', 'gobichettipalayam', 47, (SELECT id FROM districts WHERE slug = 'erode'), 'general'),
  ('Bhavanisagar', 'bhavanisagar', 48, (SELECT id FROM districts WHERE slug = 'erode'), 'sc'),
  ('Udhagamandalam', 'udhagamandalam', 49, (SELECT id FROM districts WHERE slug = 'nilgiris'), 'general'),
  ('Gudalur', 'gudalur', 50, (SELECT id FROM districts WHERE slug = 'nilgiris'), 'st'),
  ('Mettuppalayam', 'mettuppalayam', 51, (SELECT id FROM districts WHERE slug = 'coimbatore'), 'general'),
  ('Coimbatore (North)', 'coimbatore-north', 52, (SELECT id FROM districts WHERE slug = 'coimbatore'), 'general'),
  ('Thondamuthur', 'thondamuthur', 53, (SELECT id FROM districts WHERE slug = 'coimbatore'), 'general'),
  ('Coimbatore (South)', 'coimbatore-south', 54, (SELECT id FROM districts WHERE slug = 'coimbatore'), 'general'),
  ('Singanallur', 'singanallur', 55, (SELECT id FROM districts WHERE slug = 'coimbatore'), 'general'),
  ('Kinathukadavu', 'kinathukadavu', 56, (SELECT id FROM districts WHERE slug = 'coimbatore'), 'general'),
  ('Pollachi', 'pollachi', 57, (SELECT id FROM districts WHERE slug = 'coimbatore'), 'general'),
  ('Valparai', 'valparai', 58, (SELECT id FROM districts WHERE slug = 'coimbatore'), 'sc'),
  ('Sulur', 'sulur', 59, (SELECT id FROM districts WHERE slug = 'coimbatore'), 'general'),
  ('Tiruppur (North)', 'tiruppur-north', 60, (SELECT id FROM districts WHERE slug = 'tiruppur'), 'general'),
  ('Tiruppur (South)', 'tiruppur-south', 61, (SELECT id FROM districts WHERE slug = 'tiruppur'), 'general'),
  ('Palladam', 'palladam', 62, (SELECT id FROM districts WHERE slug = 'tiruppur'), 'general'),
  ('Udumalaipettai', 'udumalaipettai', 63, (SELECT id FROM districts WHERE slug = 'tiruppur'), 'general'),
  ('Madathukulam', 'madathukulam', 64, (SELECT id FROM districts WHERE slug = 'tiruppur'), 'sc'),
  ('Aravakurichi', 'aravakurichi', 65, (SELECT id FROM districts WHERE slug = 'karur'), 'general'),
  ('Karur', 'karur', 66, (SELECT id FROM districts WHERE slug = 'karur'), 'general'),
  ('Krishnarayapuram', 'krishnarayapuram', 67, (SELECT id FROM districts WHERE slug = 'karur'), 'sc'),
  ('Kulithalai', 'kulithalai', 68, (SELECT id FROM districts WHERE slug = 'karur'), 'general'),
  ('Manapparai', 'manapparai', 69, (SELECT id FROM districts WHERE slug = 'tiruchirappalli'), 'general'),
  ('Srirangam', 'srirangam', 70, (SELECT id FROM districts WHERE slug = 'tiruchirappalli'), 'general'),
  ('Tiruchirappalli (West)', 'tiruchirappalli-west', 71, (SELECT id FROM districts WHERE slug = 'tiruchirappalli'), 'general'),
  ('Tiruchirappalli (East)', 'tiruchirappalli-east', 72, (SELECT id FROM districts WHERE slug = 'tiruchirappalli'), 'general'),
  ('Thiruverambur', 'thiruverambur', 73, (SELECT id FROM districts WHERE slug = 'tiruchirappalli'), 'sc'),
  ('Lalgudi', 'lalgudi', 74, (SELECT id FROM districts WHERE slug = 'tiruchirappalli'), 'general'),
  ('Manachanallur', 'manachanallur', 75, (SELECT id FROM districts WHERE slug = 'tiruchirappalli'), 'general'),
  ('Musiri', 'musiri', 76, (SELECT id FROM districts WHERE slug = 'tiruchirappalli'), 'general'),
  ('Thuraiyur', 'thuraiyur', 77, (SELECT id FROM districts WHERE slug = 'tiruchirappalli'), 'general'),
  ('Perambalur', 'perambalur', 78, (SELECT id FROM districts WHERE slug = 'perambalur'), 'general'),
  ('Kunnam', 'kunnam', 79, (SELECT id FROM districts WHERE slug = 'perambalur'), 'sc'),
  ('Ariyalur', 'ariyalur', 80, (SELECT id FROM districts WHERE slug = 'ariyalur'), 'general'),
  ('Jayankondam', 'jayankondam', 81, (SELECT id FROM districts WHERE slug = 'ariyalur'), 'general'),
  ('Virudhachalam', 'virudhachalam', 82, (SELECT id FROM districts WHERE slug = 'cuddalore'), 'general'),
  ('Neyveli', 'neyveli', 83, (SELECT id FROM districts WHERE slug = 'cuddalore'), 'sc'),
  ('Panruti', 'panruti', 84, (SELECT id FROM districts WHERE slug = 'cuddalore'), 'general'),
  ('Cuddalore', 'cuddalore', 85, (SELECT id FROM districts WHERE slug = 'cuddalore'), 'general'),
  ('Kurinjipadi', 'kurinjipadi', 86, (SELECT id FROM districts WHERE slug = 'cuddalore'), 'general'),
  ('Bhuvanagiri', 'bhuvanagiri', 87, (SELECT id FROM districts WHERE slug = 'cuddalore'), 'general'),
  ('Chidambaram', 'chidambaram', 88, (SELECT id FROM districts WHERE slug = 'cuddalore'), 'general'),
  ('Kattumannarkoil', 'kattumannarkoil', 89, (SELECT id FROM districts WHERE slug = 'cuddalore'), 'sc'),
  ('Kallakurichi', 'kallakurichi', 90, (SELECT id FROM districts WHERE slug = 'kallakurichi'), 'general'),
  ('Gangavalli', 'gangavalli', 91, (SELECT id FROM districts WHERE slug = 'kallakurichi'), 'sc'),
  ('Attur', 'attur', 92, (SELECT id FROM districts WHERE slug = 'salem'), 'general'),
  ('Yercaud', 'yercaud', 93, (SELECT id FROM districts WHERE slug = 'salem'), 'st'),
  ('Olapadi', 'olapadi', 94, (SELECT id FROM districts WHERE slug = 'salem'), 'sc'),
  ('Tiruvannamalai', 'tiruvannamalai', 95, (SELECT id FROM districts WHERE slug = 'tiruvannamalai'), 'general'),
  ('Kilpennathur', 'kilpennathur', 96, (SELECT id FROM districts WHERE slug = 'tiruvannamalai'), 'general'),
  ('Kalasapakkam', 'kalasapakkam', 97, (SELECT id FROM districts WHERE slug = 'tiruvannamalai'), 'sc'),
  ('Polur', 'polur', 98, (SELECT id FROM districts WHERE slug = 'tiruvannamalai'), 'general'),
  ('Arani', 'arani', 99, (SELECT id FROM districts WHERE slug = 'tiruvannamalai'), 'general'),
  ('Cheyyar', 'cheyyar', 100, (SELECT id FROM districts WHERE slug = 'tiruvannamalai'), 'sc'),
  ('Vandavasi', 'vandavasi', 101, (SELECT id FROM districts WHERE slug = 'tiruvannamalai'), 'general'),
  ('Gingee', 'gingee', 102, (SELECT id FROM districts WHERE slug = 'villupuram'), 'general'),
  ('Mailam', 'mailam', 103, (SELECT id FROM districts WHERE slug = 'villupuram'), 'general'),
  ('Tindivanam', 'tindivanam', 104, (SELECT id FROM districts WHERE slug = 'villupuram'), 'general'),
  ('Vanur', 'vanur', 105, (SELECT id FROM districts WHERE slug = 'villupuram'), 'sc'),
  ('Villupuram', 'villupuram', 106, (SELECT id FROM districts WHERE slug = 'villupuram'), 'general'),
  ('Vikravandi', 'vikravandi', 107, (SELECT id FROM districts WHERE slug = 'villupuram'), 'sc'),
  ('Tirukoilur', 'tirukoilur', 108, (SELECT id FROM districts WHERE slug = 'villupuram'), 'general'),
  ('Ulundurpet', 'ulundurpet', 109, (SELECT id FROM districts WHERE slug = 'kallakurichi'), 'general'),
  ('Sankarapuram', 'sankarapuram', 110, (SELECT id FROM districts WHERE slug = 'kallakurichi'), 'general'),
  ('Rishivandiyam', 'rishivandiyam', 111, (SELECT id FROM districts WHERE slug = 'kallakurichi'), 'sc'),
  ('Vriddhachalam', 'vriddhachalam', 112, (SELECT id FROM districts WHERE slug = 'cuddalore'), 'general'),
  ('Neyveli (Township)', 'neyveli-township', 113, (SELECT id FROM districts WHERE slug = 'cuddalore'), 'general'),
  ('Sirkazhi', 'sirkazhi', 114, (SELECT id FROM districts WHERE slug = 'nagapattinam'), 'general'),
  ('Mayiladuthurai', 'mayiladuthurai', 115, (SELECT id FROM districts WHERE slug = 'mayiladuthurai'), 'general'),
  ('Poompuhar', 'poompuhar', 116, (SELECT id FROM districts WHERE slug = 'mayiladuthurai'), 'sc'),
  ('Papanasam', 'papanasam', 117, (SELECT id FROM districts WHERE slug = 'thanjavur'), 'general'),
  ('Thiruvidaimarudur', 'thiruvidaimarudur', 118, (SELECT id FROM districts WHERE slug = 'thanjavur'), 'sc'),
  ('Kumbakonam', 'kumbakonam', 119, (SELECT id FROM districts WHERE slug = 'thanjavur'), 'general'),
  ('Papanasam', 'papanasam-2', 120, (SELECT id FROM districts WHERE slug = 'thanjavur'), 'general'),
  ('Thanjavur', 'thanjavur', 121, (SELECT id FROM districts WHERE slug = 'thanjavur'), 'general'),
  ('Orathanadu', 'orathanadu', 122, (SELECT id FROM districts WHERE slug = 'thanjavur'), 'sc'),
  ('Pattukkottai', 'pattukkottai', 123, (SELECT id FROM districts WHERE slug = 'thanjavur'), 'general'),
  ('Peravurani', 'peravurani', 124, (SELECT id FROM districts WHERE slug = 'thanjavur'), 'general'),
  ('Gandharvakottai', 'gandharvakottai', 125, (SELECT id FROM districts WHERE slug = 'pudukkottai'), 'sc'),
  ('Viralimalai', 'viralimalai', 126, (SELECT id FROM districts WHERE slug = 'pudukkottai'), 'general'),
  ('Pudukkottai', 'pudukkottai', 127, (SELECT id FROM districts WHERE slug = 'pudukkottai'), 'general'),
  ('Thirumayam', 'thirumayam', 128, (SELECT id FROM districts WHERE slug = 'pudukkottai'), 'general'),
  ('Alangudi', 'alangudi', 129, (SELECT id FROM districts WHERE slug = 'pudukkottai'), 'sc'),
  ('Aranthangi', 'aranthangi', 130, (SELECT id FROM districts WHERE slug = 'pudukkottai'), 'general'),
  ('Manamelkudi', 'manamelkudi', 131, (SELECT id FROM districts WHERE slug = 'pudukkottai'), 'general'),
  ('Mannargudi', 'mannargudi', 132, (SELECT id FROM districts WHERE slug = 'thiruvarur'), 'general'),
  ('Thiruvarur', 'thiruvarur', 133, (SELECT id FROM districts WHERE slug = 'thiruvarur'), 'sc'),
  ('Nannilam', 'nannilam', 134, (SELECT id FROM districts WHERE slug = 'thiruvarur'), 'general'),
  ('Vedaranyam', 'vedaranyam', 135, (SELECT id FROM districts WHERE slug = 'nagapattinam'), 'sc'),
  ('Kilvelur', 'kilvelur', 136, (SELECT id FROM districts WHERE slug = 'nagapattinam'), 'general'),
  ('Nagapattinam', 'nagapattinam', 137, (SELECT id FROM districts WHERE slug = 'nagapattinam'), 'general'),
  ('Sembanarkoil', 'sembanarkoil', 138, (SELECT id FROM districts WHERE slug = 'nagapattinam'), 'general'),
  ('Thalaignayiru', 'thalaignayiru', 139, (SELECT id FROM districts WHERE slug = 'nagapattinam'), 'sc'),
  ('Sirkazhi', 'sirkazhi-2', 140, (SELECT id FROM districts WHERE slug = 'nagapattinam'), 'general'),
  ('Karaikal (North)', 'karaikal-north', 141, (SELECT id FROM districts WHERE slug = 'nagapattinam'), 'general'),
  ('Karaikal (South)', 'karaikal-south', 142, (SELECT id FROM districts WHERE slug = 'nagapattinam'), 'sc'),
  ('Ramanathapuram', 'ramanathapuram', 143, (SELECT id FROM districts WHERE slug = 'ramanathapuram'), 'general'),
  ('Paramakudi', 'paramakudi', 144, (SELECT id FROM districts WHERE slug = 'ramanathapuram'), 'sc'),
  ('Tiruvadanai', 'tiruvadanai', 145, (SELECT id FROM districts WHERE slug = 'ramanathapuram'), 'general'),
  ('Mudukulathur', 'mudukulathur', 146, (SELECT id FROM districts WHERE slug = 'ramanathapuram'), 'general'),
  ('Vilathikulam', 'vilathikulam', 147, (SELECT id FROM districts WHERE slug = 'thoothukudi'), 'sc'),
  ('Thoothukudi', 'thoothukudi', 148, (SELECT id FROM districts WHERE slug = 'thoothukudi'), 'general'),
  ('Tiruchendur', 'tiruchendur', 149, (SELECT id FROM districts WHERE slug = 'thoothukudi'), 'general'),
  ('Srivaikuntam', 'srivaikuntam', 150, (SELECT id FROM districts WHERE slug = 'thoothukudi'), 'general'),
  ('Ottapidaram', 'ottapidaram', 151, (SELECT id FROM districts WHERE slug = 'thoothukudi'), 'sc'),
  ('Kovilpatti', 'kovilpatti', 152, (SELECT id FROM districts WHERE slug = 'thoothukudi'), 'general'),
  ('Erachakulam', 'erachakulam', 153, (SELECT id FROM districts WHERE slug = 'thoothukudi'), 'general'),
  ('Sankarankovil', 'sankarankovil', 154, (SELECT id FROM districts WHERE slug = 'virudhunagar'), 'general'),
  ('Sivakasi', 'sivakasi', 155, (SELECT id FROM districts WHERE slug = 'virudhunagar'), 'general'),
  ('Virudhunagar', 'virudhunagar', 156, (SELECT id FROM districts WHERE slug = 'virudhunagar'), 'sc'),
  ('Aruppukkottai', 'aruppukkottai', 157, (SELECT id FROM districts WHERE slug = 'virudhunagar'), 'general'),
  ('Rajapalayam', 'rajapalayam', 158, (SELECT id FROM districts WHERE slug = 'virudhunagar'), 'general'),
  ('Srivilliputhur', 'srivilliputhur', 159, (SELECT id FROM districts WHERE slug = 'virudhunagar'), 'general'),
  ('Sattur', 'sattur', 160, (SELECT id FROM districts WHERE slug = 'virudhunagar'), 'sc'),
  ('Sivaganga', 'sivaganga', 161, (SELECT id FROM districts WHERE slug = 'sivaganga'), 'sc'),
  ('Manamadurai', 'manamadurai', 162, (SELECT id FROM districts WHERE slug = 'sivaganga'), 'general'),
  ('Karaikudi', 'karaikudi', 163, (SELECT id FROM districts WHERE slug = 'sivaganga'), 'general'),
  ('Tiruppattur', 'tiruppattur', 164, (SELECT id FROM districts WHERE slug = 'sivaganga'), 'general'),
  ('Madurai (East)', 'madurai-east', 165, (SELECT id FROM districts WHERE slug = 'madurai'), 'general'),
  ('Madurai (Central)', 'madurai-central', 166, (SELECT id FROM districts WHERE slug = 'madurai'), 'general'),
  ('Madurai (West)', 'madurai-west', 167, (SELECT id FROM districts WHERE slug = 'madurai'), 'general'),
  ('Madurai (South)', 'madurai-south', 168, (SELECT id FROM districts WHERE slug = 'madurai'), 'sc'),
  ('Madurai (North)', 'madurai-north', 169, (SELECT id FROM districts WHERE slug = 'madurai'), 'general'),
  ('Sholavandan', 'sholavandan', 170, (SELECT id FROM districts WHERE slug = 'madurai'), 'sc'),
  ('Thirparappu', 'thirparappu', 171, (SELECT id FROM districts WHERE slug = 'madurai'), 'general'),
  ('Melur', 'melur', 172, (SELECT id FROM districts WHERE slug = 'madurai'), 'general'),
  ('Usilampatti', 'usilampatti', 173, (SELECT id FROM districts WHERE slug = 'madurai'), 'sc'),
  ('Andipatti', 'andipatti', 174, (SELECT id FROM districts WHERE slug = 'theni'), 'general'),
  ('Periyakulam', 'periyakulam', 175, (SELECT id FROM districts WHERE slug = 'theni'), 'general'),
  ('Bodinayakanur', 'bodinayakanur', 176, (SELECT id FROM districts WHERE slug = 'theni'), 'sc'),
  ('Cumbum', 'cumbum', 177, (SELECT id FROM districts WHERE slug = 'theni'), 'general'),
  ('Dindigul', 'dindigul', 178, (SELECT id FROM districts WHERE slug = 'dindigul'), 'general'),
  ('Natham', 'natham', 179, (SELECT id FROM districts WHERE slug = 'dindigul'), 'sc'),
  ('Nilakottai', 'nilakottai', 180, (SELECT id FROM districts WHERE slug = 'dindigul'), 'general'),
  ('Oddanchatram', 'oddanchatram', 181, (SELECT id FROM districts WHERE slug = 'dindigul'), 'general'),
  ('Palani', 'palani', 182, (SELECT id FROM districts WHERE slug = 'dindigul'), 'general'),
  ('Vedasandur', 'vedasandur', 183, (SELECT id FROM districts WHERE slug = 'dindigul'), 'general'),
  ('Attur', 'attur-2', 184, (SELECT id FROM districts WHERE slug = 'salem'), 'general'),
  ('Tirunelveli', 'tirunelveli', 185, (SELECT id FROM districts WHERE slug = 'tirunelveli'), 'general'),
  ('Ambasamudram', 'ambasamudram', 186, (SELECT id FROM districts WHERE slug = 'tirunelveli'), 'general'),
  ('Nanguneri', 'nanguneri', 187, (SELECT id FROM districts WHERE slug = 'tirunelveli'), 'sc'),
  ('Radhapuram', 'radhapuram', 188, (SELECT id FROM districts WHERE slug = 'tirunelveli'), 'general'),
  ('Tenkasi', 'tenkasi', 189, (SELECT id FROM districts WHERE slug = 'tenkasi'), 'general'),
  ('Alangulam', 'alangulam', 190, (SELECT id FROM districts WHERE slug = 'tenkasi'), 'sc'),
  ('Kadayanallur', 'kadayanallur', 191, (SELECT id FROM districts WHERE slug = 'tenkasi'), 'general'),
  ('Sankarankovil', 'sankarankovil-2', 192, (SELECT id FROM districts WHERE slug = 'virudhunagar'), 'general'),
  ('Nagercoil', 'nagercoil', 193, (SELECT id FROM districts WHERE slug = 'kanniyakumari'), 'general'),
  ('Colachel', 'colachel', 194, (SELECT id FROM districts WHERE slug = 'kanniyakumari'), 'general'),
  ('Padmanabhapuram', 'padmanabhapuram', 195, (SELECT id FROM districts WHERE slug = 'kanniyakumari'), 'sc'),
  ('Vilavancode', 'vilavancode', 196, (SELECT id FROM districts WHERE slug = 'kanniyakumari'), 'general'),
  ('Killiyoor', 'killiyoor', 197, (SELECT id FROM districts WHERE slug = 'kanniyakumari'), 'general'),
  ('Kanyakumari', 'kanyakumari', 198, (SELECT id FROM districts WHERE slug = 'kanniyakumari'), 'general'),
  ('Thiruvottiyur', 'thiruvottiyur', 199, (SELECT id FROM districts WHERE slug = 'chennai'), 'sc'),
  ('Dr. Radhakrishnan Nagar', 'dr-radhakrishnan-nagar', 200, (SELECT id FROM districts WHERE slug = 'chennai'), 'general'),
  ('Perambur', 'perambur', 201, (SELECT id FROM districts WHERE slug = 'chennai'), 'general'),
  ('Kolathur', 'kolathur', 202, (SELECT id FROM districts WHERE slug = 'chennai'), 'general'),
  ('Villivakkam', 'villivakkam', 203, (SELECT id FROM districts WHERE slug = 'chennai'), 'general'),
  ('Thiru-Vi-Ka Nagar', 'thiru-vi-ka-nagar', 204, (SELECT id FROM districts WHERE slug = 'chennai'), 'sc'),
  ('Egmore', 'egmore', 205, (SELECT id FROM districts WHERE slug = 'chennai'), 'general'),
  ('Royapuram', 'royapuram', 206, (SELECT id FROM districts WHERE slug = 'chennai'), 'general'),
  ('Harbour', 'harbour', 207, (SELECT id FROM districts WHERE slug = 'chennai'), 'sc'),
  ('Chepauk-Triplicane', 'chepauk-triplicane', 208, (SELECT id FROM districts WHERE slug = 'chennai'), 'general'),
  ('Thousand Lights', 'thousand-lights', 209, (SELECT id FROM districts WHERE slug = 'chennai'), 'general'),
  ('Anna Nagar', 'anna-nagar', 210, (SELECT id FROM districts WHERE slug = 'chennai'), 'general'),
  ('Virugambakkam', 'virugambakkam', 211, (SELECT id FROM districts WHERE slug = 'chennai'), 'general'),
  ('Saidapet', 'saidapet', 212, (SELECT id FROM districts WHERE slug = 'chennai'), 'sc'),
  ('Thiyagarayanagar', 'thiyagarayanagar', 213, (SELECT id FROM districts WHERE slug = 'chennai'), 'general'),
  ('Mylapore', 'mylapore', 214, (SELECT id FROM districts WHERE slug = 'chennai'), 'general'),
  ('Velachery', 'velachery', 215, (SELECT id FROM districts WHERE slug = 'chennai'), 'general'),
  ('Sholinganallur', 'sholinganallur', 216, (SELECT id FROM districts WHERE slug = 'chennai'), 'general'),
  ('Alandur', 'alandur', 217, (SELECT id FROM districts WHERE slug = 'chengalpattu'), 'general'),
  ('Sriperumbudur', 'sriperumbudur', 218, (SELECT id FROM districts WHERE slug = 'kancheepuram'), 'sc'),
  ('Pallavaram', 'pallavaram', 219, (SELECT id FROM districts WHERE slug = 'chengalpattu'), 'general'),
  ('Tambaram', 'tambaram', 220, (SELECT id FROM districts WHERE slug = 'chengalpattu'), 'general'),
  ('Chengalpattu', 'chengalpattu', 221, (SELECT id FROM districts WHERE slug = 'chengalpattu'), 'general'),
  ('Thiruporur', 'thiruporur', 222, (SELECT id FROM districts WHERE slug = 'chengalpattu'), 'general'),
  ('Cheyyur', 'cheyyur', 223, (SELECT id FROM districts WHERE slug = 'chengalpattu'), 'sc'),
  ('Madurantakam', 'madurantakam', 224, (SELECT id FROM districts WHERE slug = 'chengalpattu'), 'general'),
  ('Uthiramerur', 'uthiramerur', 225, (SELECT id FROM districts WHERE slug = 'kancheepuram'), 'general'),
  ('Kancheepuram', 'kancheepuram', 226, (SELECT id FROM districts WHERE slug = 'kancheepuram'), 'sc'),
  ('Arakkonam', 'arakkonam', 227, (SELECT id FROM districts WHERE slug = 'ranipet'), 'sc'),
  ('Sholingur', 'sholingur-2', 228, (SELECT id FROM districts WHERE slug = 'vellore'), 'general'),
  ('Thiruvallur', 'thiruvallur', 229, (SELECT id FROM districts WHERE slug = 'thiruvallur'), 'general'),
  ('Poonamallee', 'poonamallee', 230, (SELECT id FROM districts WHERE slug = 'thiruvallur'), 'sc'),
  ('Avadi', 'avadi', 231, (SELECT id FROM districts WHERE slug = 'thiruvallur'), 'general'),
  ('Maduravoyal', 'maduravoyal', 232, (SELECT id FROM districts WHERE slug = 'thiruvallur'), 'general'),
  ('Ambattur', 'ambattur', 233, (SELECT id FROM districts WHERE slug = 'thiruvallur'), 'general'),
  ('Madavaram', 'madavaram', 234, (SELECT id FROM districts WHERE slug = 'thiruvallur'), 'general')
ON CONFLICT (slug) DO NOTHING;

-- Section 4: Candidates (7 rows)
INSERT INTO candidates (full_name, slug, date_of_birth, gender, education) VALUES
  ('M K Stalin', 'mk-stalin', '1953-03-01', 'male', 'Graduate'),
  ('Edappadi K Palaniswami', 'edappadi-k-palaniswami', '1953-03-25', 'male', 'Graduate'),
  ('O Panneerselvam', 'o-panneerselvam', '1952-11-18', 'male', 'Class X'),
  ('Seeman', 'seeman', '1974-02-14', 'male', 'B.Com'),
  ('Annamalai K', 'annamalai-k', '1984-07-30', 'male', 'MBA'),
  ('Thol Thirumavalavan', 'thol-thirumavalavan', '1965-05-17', 'male', 'Graduate'),
  ('Vijay (Thalapathy)', 'vijay-thalapathy', '1974-06-22', 'male', 'B.Sc')
ON CONFLICT (slug) DO NOTHING;

-- Section 5: Election Contests (7 rows)
INSERT INTO election_contests (candidate_id, constituency_id, party_id, election_year, is_current_election, assets_movable_lakh, assets_immovable_lakh, liabilities_lakh, criminal_cases_pending) VALUES
  ((SELECT id FROM candidates WHERE slug = 'mk-stalin'), (SELECT id FROM constituencies WHERE slug = 'kolathur'), (SELECT id FROM parties WHERE abbreviation = 'DMK'), 2026, true, 245.5, 1820.3, 0, 0),
  ((SELECT id FROM candidates WHERE slug = 'edappadi-k-palaniswami'), (SELECT id FROM constituencies WHERE slug = 'edappadi'), (SELECT id FROM parties WHERE abbreviation = 'AIADMK'), 2026, true, 180.2, 950.0, 0, 0),
  ((SELECT id FROM candidates WHERE slug = 'o-panneerselvam'), (SELECT id FROM constituencies WHERE slug = 'bodinayakanur'), (SELECT id FROM parties WHERE abbreviation = 'AIADMK'), 2026, true, 320.1, 2100.5, 0, 0),
  ((SELECT id FROM candidates WHERE slug = 'seeman'), (SELECT id FROM constituencies WHERE slug = 'harbour'), (SELECT id FROM parties WHERE abbreviation = 'NTK'), 2026, true, 12.3, 45.0, 0, 2),
  ((SELECT id FROM candidates WHERE slug = 'annamalai-k'), (SELECT id FROM constituencies WHERE slug = 'coimbatore-south'), (SELECT id FROM parties WHERE abbreviation = 'BJP'), 2026, true, 35.8, 120.5, 0, 3),
  ((SELECT id FROM candidates WHERE slug = 'thol-thirumavalavan'), (SELECT id FROM constituencies WHERE slug = 'chidambaram'), (SELECT id FROM parties WHERE abbreviation = 'VCK'), 2026, true, 8.5, 32.1, 0, 1),
  ((SELECT id FROM candidates WHERE slug = 'vijay-thalapathy'), (SELECT id FROM constituencies WHERE slug = 'vilavancode'), (SELECT id FROM parties WHERE abbreviation = 'TVK'), 2026, true, 425.0, 2800.0, 0, 0);

-- Section 6: Refresh search index
REFRESH MATERIALIZED VIEW search_index;
